### ISSUE TITLE
Problems with adding questions

### ISSUE THREAD

**Issue by SirLupus** [kilianr/phpbb-ext-survey#1] opened 2015-12-04 13:27 UTC
Hi,

I created a new topic with the option to enable the survey. After that I tried to add some questions, so I went to "Fragen verwalten". No matter what I try to put in the fields I always get the message "Das übermittelte Formular war ungültig. Versuche erneut, das Formular abzusenden.".

Is there any workaround?

Thank you!

**Comment by kilianr** [comment] 2016-01-04 14:36
I cannot reproduce this issue. Can you please provide more Information about:
- git version of the survey that you have installed
- survey extension permissions in the forum

Thanks.

**Comment by SirLupus** [comment] 2016-01-04 16:50
Ext: 1.0 RC1
PhpBB: 3.1.6

Installed a fresh forum and only this extension just to be sure. 

Go to ACP -> General -> Board Features:  Set Yes to Allow quick reply.  And submit and enable in all forums.

This should enable the problem for your (hopefully). That's all I did in a clean, freshly installed forum.

**Comment by kilianr** [comment] 2016-01-04 16:55
Ok, there seems to be a problem with the extension in combination with quick reply. I will investigate it.

**Comment by kilianr** [comment] 2016-01-04 17:56
So, this should be fixed.

Basically this wasn't an issue of the extension but of the design of form protection in phpBB itself. Sadly, there is no option in add_form_key to specify a custom template-variable name. So you always have to use S_FORM_TOKEN which leads to collisions, if you have more than one protected form on one page, as was the case here.
To solve this, I added a hook for the add_form_key function in order to assign the content of my call to add_form_key to a second, name-customized template variable that I use now for my protected forms in viewtopic.php.

An option to customize the template-variable name directly when calling add_form_key should be added to the phpBB core. I will write an patch and submit a pull request, when I have time...

**Closed as completed by kilianr** 2016-01-04 17:56 UTC
